services:
    kyahuapathe:
        container_name: kyahuapathe
        build: .
        env_file:
            - .env
        ports:
            - ${AGENT_PORT}:${AGENT_PORT}
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./src:/app/src

    pathe_db:
        container_name: kyahuapathe_db
        image: postgres:17.7-alpine
        env_file:
            - .env
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data